### PR TITLE
patch for function arg/return types in `frontier_client.py`

### PR DESCRIPTION
**Pull request by missirol**
Patch resulted from the debugging done in https://github.com/cms-sw/cmssw/issues/33945 (mostly carried out by others before me).

Aims to solve failure of some unit tests in ASAN IBs of CMSSW (see https://github.com/cms-sw/cmssw/issues/33945 for further details).

Opening this PR to test the patch, as suggested by @smuzaffar.

### CODE REVIEW

**Comment by missirol** [comment]
@smuzaffar

If possible, it might be useful to test first only the package `CondTools/HLT`, because for that one there is only 1 unit test that fails in ASAN IBs, and that one should be fixed by this patch. Most other packages also contain other unrelated unit-test failures that this patch does not fix (so the tests would likely fail anyways). In general, if the patch works, there should be no mention of `frontier_getRawData` in the unit-test logs.

**Comment by smuzaffar** [comment]
test parameters:
- addpkg = CondTools, CondCore/Utilities, CommonTools/Utils, Alignment

**Comment by smuzaffar** [comment]
please test
lets test the change for normal IBs

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_ASAN_X

**Comment by smuzaffar** [comment]
please test for CMSSW_12_3_ASAN_X

**Comment by smuzaffar** [comment]
@DrDaveD this patch seems to fix frontier client errors for CMSSW ASAN builds. Can you please review these and if looks good then can you please include this in next frontier_client release?

**Comment by smuzaffar** [comment]
+externals
looks good

**Comment by DrDaveD** [comment]
As I mentioned in cms-sw/cmsdist#7539, there is currently no frontier_client.py in the frontier client distribution, that is a cmssw addition.  Other than that the patch looks ok to me.  Perhaps it is finally time to move frontier_client.py to the frontier_client external.

**Comment by DrDaveD** [comment]
I see there was already a fermitools/frontier#37 issue to include the python bindings, as referenced at cms-sw/cmsdist#5898

**Pull request merged**
